-- ==============================================================================
-- SAPC Course Proposal System - Seed / Sample Data
-- Indian Institute of Technology Gandhinagar
-- NOTE: ALL DATA BELOW ARE FOR DEMONSTRATION / TESTING PURPOSES ONLY
-- ==============================================================================

-- 1. Initial Admin User
-- Password is 'Admin@IITGN2026' (PBKDF2 SHA256 hashed or bcrypt)
-- PBKDF2 hash for 'Admin@IITGN2026':
-- pbkdf2:sha256:600000$WvQJvL5J0x9y1mNz$7e562142e0fc394d21da2f5dbcdcbfafeef5eb1f8bebc988fa3910c266a01490
INSERT INTO admin_users (username, password_hash, role)
VALUES (
    'admin',
    'pbkdf2:sha256:600000$WvQJvL5J0x9y1mNz$7e562142e0fc394d21da2f5dbcdcbfafeef5eb1f8bebc988fa3910c266a01490',
    'Academic Office'
) ON CONFLICT (username) DO NOTHING;

-- 2. Initial Configurable Deadline Settings
-- Default window opens today and closes in 15 days
INSERT INTO deadline_settings (
    submission_start,
    submission_deadline,
    is_active,
    announcement_message,
    updated_by
)
VALUES (
    CURRENT_TIMESTAMP - INTERVAL '2 days',
    CURRENT_TIMESTAMP + INTERVAL '14 days',
    TRUE,
    'SAPC Course Proposal Submissions for the upcoming Academic Semester are now OPEN. All submissions must be received before the deadline.',
    'Academic Office Admin'
);

-- 3. Realistic Demo Course Proposals (Clearly marked as DEMO / SAMPLE DATA)

-- Sample 1: New Advanced Computer Science Course (Level 4, BTech/MTech)
INSERT INTO proposals (
    proposal_id,
    submission_date,
    status,
    course_title,
    potential_instructors,
    proposer_name,
    faculty_email,
    course_type,
    course_type_other,
    course_level,
    course_level_secondary,
    course_l_t_p_c,
    lecture_hours,
    tutorial_hours,
    practical_hours,
    credits,
    course_duration,
    expected_frequency,
    elective_basket_btech,
    discipline_elective_btech,
    discipline_basket_btech,
    minors,
    minor_basket_thematic_area,
    discipline_elective_msc,
    courses_discipline_mtech,
    mtech_sub_specialization,
    discipline_elective_mdes,
    is_modification,
    existing_course_code,
    prior_knowledge,
    course_contents,
    texts_and_references,
    learning_outcomes,
    overlap_courses,
    other_relevant_info,
    pdf_path,
    pdf_filename,
    email_notification_status
) VALUES (
    'SAPC-2026-0001',
    CURRENT_TIMESTAMP - INTERVAL '36 hours',
    'Approved',
    'DEMO / SAMPLE DATA: Distributed Systems and Cloud Computing',
    'Dr. Vikram Sharma; Dr. Ananya Sen',
    'Dr. Vikram Sharma',
    'vikram.sharma@demo.iitgn.ac.in',
    'CS',
    NULL,
    '4',
    '6',
    '3-0-2-4',
    3.0,
    0.0,
    2.0,
    4.0,
    '4 Quads (Full Semester)',
    'Each Year',
    NULL,
    'CS',
    'Systems and Networking Basket',
    'CS, DA',
    'High Performance Computing',
    NULL,
    'CS',
    'Distributed Systems Specialization',
    NULL,
    FALSE,
    NULL,
    'Data Structures and Algorithms; Basic Computer Networks; Operating Systems fundamentals',
    'Introduction to distributed system models; Inter-process communication and remote procedure calls; Logical clocks, vector clocks, and causal ordering; Distributed mutual exclusion algorithms; Consensus protocols including Paxos and Raft; Fault tolerance and replication architectures; Distributed file systems and key-value stores; Cloud resource virtualization and container orchestration.',
    '1. Coulouris, G., Dollimore, J., & Kindberg, T. (2012). Distributed Systems: Concepts and Design (5th ed.). Addison-Wesley.; 2. Tanenbaum, A. S., & Van Steen, M. (2017). Distributed Systems: Principles and Paradigms (3rd ed.). CreateSpace.',
    'Students will be able to: 1. Formulate and analyze consistency models in distributed environments; 2. Implement consensus algorithms such as Raft; 3. Architect fault-tolerant distributed services using modern container clusters; 4. Evaluate latency-throughput trade-offs under high network concurrency.',
    'Minor conceptual overlap (approx 10%) with Operating Systems in process synchronization; no significant overlap with other approved courses.',
    'Includes hands-on engineering lab projects using Go and Kubernetes. Highly relevant for cloud infrastructure industry and systems research.',
    'generated_pdfs/SAPC-2026-0001.pdf',
    'SAPC-2026-0001.pdf',
    'Sent'
);

-- Sample 2: Modification of an Existing Electrical Engineering Course
INSERT INTO proposals (
    proposal_id,
    submission_date,
    status,
    course_title,
    potential_instructors,
    proposer_name,
    faculty_email,
    course_type,
    course_type_other,
    course_level,
    course_level_secondary,
    course_l_t_p_c,
    lecture_hours,
    tutorial_hours,
    practical_hours,
    credits,
    course_duration,
    expected_frequency,
    elective_basket_btech,
    discipline_elective_btech,
    discipline_basket_btech,
    minors,
    minor_basket_thematic_area,
    discipline_elective_msc,
    courses_discipline_mtech,
    mtech_sub_specialization,
    discipline_elective_mdes,
    is_modification,
    existing_course_code,
    prior_knowledge,
    course_contents,
    texts_and_references,
    learning_outcomes,
    overlap_courses,
    other_relevant_info,
    pdf_path,
    pdf_filename,
    email_notification_status
) VALUES (
    'SAPC-2026-0002',
    CURRENT_TIMESTAMP - INTERVAL '20 hours',
    'Under Review',
    'DEMO / SAMPLE DATA: Digital Signal Processing for Communications',
    'Prof. K. Rameshwar',
    'Prof. K. Rameshwar',
    'k.rameshwar@demo.iitgn.ac.in',
    'EE',
    NULL,
    '3',
    NULL,
    '3-1-0-4',
    3.0,
    1.0,
    0.0,
    4.0,
    '4 Quads (Full Semester)',
    'Each Semester',
    NULL,
    'EE',
    'Signal Processing and Communications',
    'EE, ICDT',
    'Signal Processing Thematic Area',
    NULL,
    'EE',
    'Communications Engineering',
    NULL,
    TRUE,
    'EE-302',
    'Signals and Systems (EE-201); Engineering Mathematics (Linear Algebra and Complex Variables)',
    'Review of discrete-time signals and systems; Z-transform and system functions; Discrete Fourier Transform (DFT) and Fast Fourier Transform (FFT) computational structures; Design of Finite Impulse Response (FIR) filters; Design of Infinite Impulse Response (IIR) filters; Multi-rate digital signal processing and filter banks; Modern adaptive filtering algorithms; Applications in 5G wireless channel estimation.',
    '1. Oppenheim, A. V., & Schafer, R. W. (2010). Discrete-Time Signal Processing (3rd ed.). Pearson.; 2. Proakis, J. G., & Manolakis, D. G. (2007). Digital Signal Processing: Principles, Algorithms, and Applications (4th ed.). Prentice Hall.',
    '1. Apply DFT/FFT algorithms to analyze complex multi-carrier signals; 2. Synthesize FIR and IIR digital filter topologies meeting industrial attenuation specifications; 3. Formulate adaptive filtering strategies for communication interference cancellation.',
    'Replaces and updates curriculum of existing EE-302 to integrate modern multi-rate signal processing and 5G modulation standards.',
    'Modification updates 30% of content to incorporate software-defined radio experiments and adaptive filtering for telecom industries.',
    'generated_pdfs/SAPC-2026-0002.pdf',
    'SAPC-2026-0002.pdf',
    'Sent'
);

-- Sample 3: New Humanities & Social Sciences Interdisciplinary Course (Level 2 UG)
INSERT INTO proposals (
    proposal_id,
    submission_date,
    status,
    course_title,
    potential_instructors,
    proposer_name,
    faculty_email,
    course_type,
    course_type_other,
    course_level,
    course_level_secondary,
    course_l_t_p_c,
    lecture_hours,
    tutorial_hours,
    practical_hours,
    credits,
    course_duration,
    expected_frequency,
    elective_basket_btech,
    discipline_elective_btech,
    discipline_basket_btech,
    minors,
    minor_basket_thematic_area,
    discipline_elective_msc,
    courses_discipline_mtech,
    mtech_sub_specialization,
    discipline_elective_mdes,
    is_modification,
    existing_course_code,
    prior_knowledge,
    course_contents,
    texts_and_references,
    learning_outcomes,
    overlap_courses,
    other_relevant_info,
    pdf_path,
    pdf_filename,
    email_notification_status
) VALUES (
    'SAPC-2026-0003',
    CURRENT_TIMESTAMP - INTERVAL '8 hours',
    'Pending',
    'DEMO / SAMPLE DATA: Technology, Ethics, and Society',
    'Dr. Maya Kulkarni',
    'Dr. Maya Kulkarni',
    'maya.kulkarni@demo.iitgn.ac.in',
    'HS',
    NULL,
    '2',
    NULL,
    '3-0-0-3',
    3.0,
    0.0,
    0.0,
    3.0,
    '4 Quads (Full Semester)',
    'Each Year',
    'HS',
    NULL,
    NULL,
    'HS, SD',
    'Ethics and Technology Policy',
    NULL,
    NULL,
    NULL,
    NULL,
    FALSE,
    NULL,
    'None required; open to all undergraduate disciplines',
    'Historical overview of technological revolutions and social transitions; Ethical frameworks: Utilitarianism, Deontology, and Virtue Ethics in technological decision making; AI governance, algorithmic bias, and automated decision systems; Surveillance capitalism, personal privacy, and data dignity; Environmental and climate implications of computational infrastructure; Bioethics and genetic enhancement policies; Public policy formulations for emerging disruptive technologies.',
    '1. Winner, L. (1986). The Whale and the Reactor: A Search for Limits in an Age of High Technology. University of Chicago Press.; 2. Sandel, M. J. (2012). What Money Can’t Buy: The Moral Limits of Markets. Farrar, Straus and Giroux.; 3. Zuboff, S. (2019). The Age of Surveillance Capitalism. PublicAffairs.',
    '1. Critique technological innovations using classical and contemporary philosophical frameworks; 2. Articulate ethical impact assessments for automated algorithmic deployments; 3. Formulate balanced policy proposals safeguarding citizen privacy and environmental equity.',
    'Complementary to CS ethics seminars; no formal curricular overlap with approved engineering courses.',
    'Fulfills the mandatory HSS Elective Basket for BTech students across all engineering branches.',
    'generated_pdfs/SAPC-2026-0003.pdf',
    'SAPC-2026-0003.pdf',
    'Pending'
);

-- Sample 4: Proposal Requiring Modification (Mechanical Engineering, Half Semester Quad)
INSERT INTO proposals (
    proposal_id,
    submission_date,
    status,
    course_title,
    potential_instructors,
    proposer_name,
    faculty_email,
    course_type,
    course_type_other,
    course_level,
    course_level_secondary,
    course_l_t_p_c,
    lecture_hours,
    tutorial_hours,
    practical_hours,
    credits,
    course_duration,
    expected_frequency,
    elective_basket_btech,
    discipline_elective_btech,
    discipline_basket_btech,
    minors,
    minor_basket_thematic_area,
    discipline_elective_msc,
    courses_discipline_mtech,
    mtech_sub_specialization,
    discipline_elective_mdes,
    is_modification,
    existing_course_code,
    prior_knowledge,
    course_contents,
    texts_and_references,
    learning_outcomes,
    overlap_courses,
    other_relevant_info,
    pdf_path,
    pdf_filename,
    email_notification_status
) VALUES (
    'SAPC-2026-0004',
    CURRENT_TIMESTAMP - INTERVAL '2 hours',
    'Modification Required',
    'DEMO / SAMPLE DATA: Rapid Prototyping and Additive Manufacturing',
    'Dr. Rajesh Nair; Dr. Priya Verma',
    'Dr. Rajesh Nair',
    'rajesh.nair@demo.iitgn.ac.in',
    'ME',
    NULL,
    '3',
    NULL,
    '2-0-2-3',
    2.0,
    0.0,
    2.0,
    3.0,
    '2 Quads (Half Semester)',
    'Each Semester',
    NULL,
    'ME',
    'Manufacturing Science Basket',
    'ME, RB',
    'Advanced Manufacturing',
    NULL,
    'ME',
    'Thermal and Design Specialization',
    NULL,
    FALSE,
    NULL,
    'Manufacturing Processes (ME-201); Mechanics of Materials',
    'Classification of additive manufacturing technologies; Stereolithography (SLA) photopolymerization processes; Fused Deposition Modeling (FDM) extrusion kinetics; Selective Laser Sintering (SLS) powder bed fusion; Design for Additive Manufacturing (DfAM) principles; Lattice structures and topology optimization; Post-processing surface treatments and metrology; Industrial applications in aerospace and biomedical implants.',
    '1. Gibson, I., Rosen, D., Stucker, B., & Khorasani, M. (2021). Additive Manufacturing Technologies (3rd ed.). Springer.; 2. Chua, C. K., & Leong, K. F. (2017). 3D Printing and Additive Manufacturing: Principles and Applications (5th ed.). World Scientific.',
    '1. Select appropriate additive manufacturing technologies based on material constraints; 2. Execute topology optimization for lightweight structural mechanical components; 3. Calibrate slicing parameters and post-processing finishing cycles.',
    'Partial overlap (approx 15%) with general manufacturing lab; specialized focus on modern 3D sintering.',
    'Reviewer note: SAPC requested clarification on lab consumable budget and machine availability before final approval.',
    'generated_pdfs/SAPC-2026-0004.pdf',
    'SAPC-2026-0004.pdf',
    'Sent'
);

-- 4. Initial Status Audit History for Samples
INSERT INTO proposal_status_history (proposal_id, previous_status, new_status, remarks, changed_by)
VALUES
    ('SAPC-2026-0001', 'Pending', 'Under Review', 'Initial formal review initiated by SAPC Committee.', 'Academic Office Admin'),
    ('SAPC-2026-0001', 'Under Review', 'Approved', 'Approved in 42nd SAPC Senate meeting without modifications.', 'Academic Office Admin'),
    ('SAPC-2026-0002', 'Pending', 'Under Review', 'Forwarded to EE discipline review committee.', 'Academic Office Admin'),
    ('SAPC-2026-0004', 'Pending', 'Modification Required', 'Please provide explicit safety protocols for laser powder sintering equipment and specify quad calendar.', 'Academic Office Admin');
